"""
LangGraph State Definition
Shared state structure for Translation Layer workflow.
See docs/translation/README.md for data flow.
"""

from typing import TypedDict, Optional, List, Dict, Any


class WorkflowState(TypedDict, total=False):
    """
    State shared across all Translation Layer nodes.
    
    Fields flow through the workflow as nodes update them:
    - correlation_id: UUIDv4 generated by Router
    - operator_input: Original natural language command
    - intent: Classification (action | question | unknown)
    - plan: Task sequence from SequenceBuilder
    - plan_attempt: Retry counter (max 3)
    - validation_errors: Planning or verification feedback
    - human_decision: approved | revision | declined | timeout
    - human_comments: Operator feedback for revision
    - verification_result: VerificationResult.to_dict()
    - yaml_sequence: Final YAML output from Robot Layer
    - execution_result: Robot execution outcome
    - response: Natural language reply (for questions/fallback)
    """
    
    # Router output
    correlation_id: str
    operator_input: str
    intent: str  # action | question | unknown
    
    # SequencePlanning output
    plan: Optional[List[Dict[str, Any]]]
    plan_attempt: int
    knowledge_snapshot: Optional[Dict[str, Any]]  # Positions/tools/routines from graph
    
    # Planning/Verification feedback
    validation_errors: Optional[str]
    
    # HumanReview output
    human_decision: Optional[str]  # approved | revision | declined | timeout
    human_comments: Optional[str]
    human_review_deadline: Optional[float]  # Unix timestamp when timeout occurs
    human_review_started_at: Optional[float]  # Unix timestamp when review started
    
    # Verification output
    verification_result: Optional[Dict[str, Any]]
    
    # Robot Layer output
    yaml_sequence: Optional[str]
    execution_result: Optional[Dict[str, Any]]
    
    # Question/Fallback output
    response: Optional[str]
