"""
Robot Node
Executes robot sequence in configured mode (simulation or socket).
YAML is already generated by verification layer (company deliverable).
See docs/robot-layer/README.md for execution protocol.
"""

from typing import Dict, Any
from src.core.translation.state import WorkflowState
from src.core.robot.executor import RobotExecutor
from src.core.observability.logging import get_logger

logger = get_logger("robot_node")

executor = RobotExecutor()

def robot_node(state: WorkflowState) -> Dict[str, Any]:
    """
    Execute robot sequence using YAML from verification layer.
    
    Args:
        state: WorkflowState containing:
            - yaml_sequence: Generated YAML actions
            - plan: Task plan for history
            - correlation_id: Run identifier
            - operator_input: Original command
            - human_comments: Optional revision feedback
    
    Returns:
        Dict with execution_result and response message
        
    Note:
        Execution mode (simulation/socket) determined by ROBOT_EXECUTION_MODE env var
    """
    correlation_id = state["correlation_id"]
    plan = state["plan"]
    yaml_sequence = state["yaml_sequence"]
    operator_input = state["operator_input"]
    human_comments = state.get("human_comments")
    
    # Build full command context (original + revision if present)
    full_command = operator_input
    if human_comments:
        full_command = f"{operator_input} (revised: {human_comments})"
    
    logger.info("Starting robot execution", 
               correlation_id=correlation_id,
               note="YAML generated by verification layer")
    

    execution_result = executor.execute_sequence(
        yaml_sequence,
        plan,
        correlation_id,
        full_command  # Pass full command with revision context
    )
    
    if execution_result["success"]:
        logger.info("Robot execution completed", correlation_id=correlation_id)
        
        response = f"Task completed successfully!\n"
        response += f"Run ID: {execution_result['run_id']}\n"
        response += f"\nYAML Sequence:\n{yaml_sequence}"
    else:
        logger.error("Robot execution failed", 
                    correlation_id=correlation_id,
                    error=execution_result["message"])
        
        response = f"Execution failed: {execution_result['message']}\n"
        response += f"Run ID: {execution_result['run_id']}"
    
    return {
        "execution_result": execution_result,
        "response": response,
    }